package clinicaveterinaria.view;

import clinicaveterinaria.model.Atendimento;
import clinicaveterinaria.model.Veterinario;
import clinicaveterinaria.model.Pet;
import clinicaveterinaria.util.GerenciadorViews; 
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.table.DefaultTableModel;

// View responsável por mostras históricos de atendimentos de pets ou veterinários
// faz uso de sobrecarga de metódos (construtor) para conseguir aceitar ambos
public class HistoricoAtendimentos extends javax.swing.JFrame {
    private final Pet petAlvo;
    private final Veterinario vetAlvo;
    private List<Atendimento> listaExibida; 

    // Construtor para Pet
    public HistoricoAtendimentos(Pet pet) {
        initComponents();
        GerenciadorViews.configurar(this);
        
        this.petAlvo = pet;
        this.vetAlvo = null; 
        
        setTitle("Histórico do Paciente: " + pet.getNome());
        carregarTabela();
    }

    // Construtor para Veterinário
    public HistoricoAtendimentos(Veterinario vet) {
        initComponents();
        GerenciadorViews.configurar(this);
        
        this.vetAlvo = vet;
        this.petAlvo = null;
        
        setTitle("Agenda do Dr(a). " + vet.getNome());
        carregarTabela();
    }
    
    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        DateTimeFormatter fmtData = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        List<Atendimento> fonteDados;
        if (petAlvo != null) {
            fonteDados = petAlvo.getHistorico();
        } else {
            fonteDados = vetAlvo.getAgendaConsultas();
        }

        this.listaExibida = new ArrayList<>(fonteDados);
        Collections.sort(this.listaExibida, (a1, a2) -> {
            int c = a2.getData().compareTo(a1.getData()); 
            if (c != 0) return c;
            return a2.getHora().compareTo(a1.getHora());
        });

        for (Atendimento a : this.listaExibida) {
            modelo.addRow(new Object[]{
                a.getVetResponsavel().getNome(),
                a.getPetAtendido().getEspecie().toString(),
                a.getPetAtendido().getNome(),
                a.getProcedimento(),
                a.getData().format(fmtData),
                a.getHora().toString(),
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Histórico de Agendamentos");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Veterinário", "Espécie", "Nome", "Atendimento", "Data", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Para visualizar clique duas vezes no agendamento desejado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    if (evt.getClickCount() == 2) {
        int linha = jTable1.getSelectedRow();
        
        if (linha != -1 && listaExibida != null && linha < listaExibida.size()) {
            
            Atendimento selecionado = listaExibida.get(linha);
            
            VisualizarAtendimento tela = new VisualizarAtendimento(selecionado);
            tela.setVisible(true);
            
            // Mantém a tabela atualizada mesmo que edições sejam feitas
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    carregarTabela();
                }
            });
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
