package clinicaveterinaria.view;

import javax.swing.JOptionPane;
import clinicaveterinaria.controller.TutorController;
import clinicaveterinaria.model.Tutor;
import clinicaveterinaria.util.GerenciadorViews;
import javax.swing.table.DefaultTableModel;

// Mostra todos os tutores do sistema
public class ListaGerenciarTutores extends javax.swing.JFrame {
    
    public ListaGerenciarTutores() {
        initComponents();
        GerenciadorViews.configurar(this);
        carregarTabela();
        
        // Garante que a lista se mantenha atualizada
        this.addWindowListener(
                new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowActivated(java.awt.event.WindowEvent e) {
                        carregarTabela();
                    }
                }
            );  
    }

    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaTutores.getModel();

        modelo.setNumRows(0);

        for (Tutor t : TutorController.getListaTutores()) {
            modelo.addRow(new Object[]{
                t.getNome()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAvançar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaTutores = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Espécie", "Nome", "Atendimento", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAvançar.setText("Avançar");
        btnAvançar.addActionListener(this::btnAvançarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Selecione um Tutor:");

        btnVoltar2.setText("Cancelar");
        btnVoltar2.addActionListener(this::btnVoltar2ActionPerformed);

        tabelaTutores.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tabelaTutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "NOME DO TUTOR:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTutores.setRowHeight(30);
        jScrollPane3.setViewportView(tabelaTutores);
        if (tabelaTutores.getColumnModel().getColumnCount() > 0) {
            tabelaTutores.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnVoltar2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAvançar))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvançar)
                    .addComponent(btnVoltar2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvançarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvançarActionPerformed
        int linhaSelecionada = tabelaTutores.getSelectedRow();
        if (linhaSelecionada != -1) {
            this.dispose();
            Tutor tutorSelecionado = TutorController.getListaTutores().get(linhaSelecionada);
            VisualizarTutor tela = new VisualizarTutor(tutorSelecionado);
            tela.setVisible(true);    
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um tutor na lista primeiro!");
        }
    }//GEN-LAST:event_btnAvançarActionPerformed

    private void btnVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvançar;
    private javax.swing.JButton btnVoltar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelaTutores;
    // End of variables declaration//GEN-END:variables
}
