package clinicaveterinaria.view;

import clinicaveterinaria.controller.AtendimentoController;
import clinicaveterinaria.model.Atendimento;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ImageIcon;


public class Menu extends javax.swing.JFrame {
    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/clinicaveterinaria/imagens/icon.png")).getImage());
        carregarAgendaDoDia();
        
        this.addWindowListener(
                new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowActivated(java.awt.event.WindowEvent e) {
                        carregarAgendaDoDia();
                    }
                }
            );  
    }

    private void carregarAgendaDoDia() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        modelo.setColumnIdentifiers(new String[] {"Veterinário", "Espécie", "Nome", "Atendimento", "Horário"});

        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");

        if (AtendimentoController.listaAtendimentos != null) {
            java.util.List<clinicaveterinaria.model.Atendimento> agendaHoje = new java.util.ArrayList<>();

            for (Atendimento a : AtendimentoController.listaAtendimentos) {
                if (a.getData().equals(hoje)) {
                    agendaHoje.add(a);
                }
            }

            Collections.sort(agendaHoje, Comparator.comparing(Atendimento::getHora));

            for (Atendimento a : agendaHoje) {
                modelo.addRow(new Object[]{
                    a.getVetResponsavel().getNome(),
                    a.getPetAtendido().getEspecie().toString(),
                    a.getPetAtendido().getNome(),
                    a.getProcedimento().name(),
                    a.getHora().format(formatoHora)
                });
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cadastrarNovoTutor = new javax.swing.JMenuItem();
        gerenciarTutores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("AGENDA DO DIA:");

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Veterinário", "Espécie", "Nome", "Atendimento", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicaveterinaria/imagens/Menu.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("(Para visualizar clique duas vezes no atendimento desejado)");

        jMenu1.setText("Cadastros");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setText("Cadastrar Novo Veterinário");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu1.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem8.setText("Gerenciar Veterinários");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator1);

        cadastrarNovoTutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarNovoTutor.setText("Cadastrar Novo Tutor");
        cadastrarNovoTutor.addActionListener(this::cadastrarNovoTutorActionPerformed);
        jMenu1.add(cadastrarNovoTutor);

        gerenciarTutores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gerenciarTutores.setText("Gerenciar Tutores");
        gerenciarTutores.addActionListener(this::gerenciarTutoresActionPerformed);
        jMenu1.add(gerenciarTutores);
        jMenu1.add(jSeparator2);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem11.setText("Cadastrar Novo Pet");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu1.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem12.setText("Gerenciar Pets");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu1.add(jMenuItem12);
        jMenu1.add(jSeparator5);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Agendamentos");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Histórico de Agendamentos");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu5.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Agendar Novo Atendimento");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu5.add(jMenuItem1);
        jMenu5.add(jSeparator3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarNovoTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoTutorActionPerformed
        CadastrarTutor novoTutor = new CadastrarTutor();
        novoTutor.setVisible(true);
    }//GEN-LAST:event_cadastrarNovoTutorActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ListaGerenciarPets tela = new ListaGerenciarPets();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void gerenciarTutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarTutoresActionPerformed
        ListaGerenciarTutores tela = new ListaGerenciarTutores();
        tela.setVisible(true);
    }//GEN-LAST:event_gerenciarTutoresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListaGerenciarAtendimentos tela = new ListaGerenciarAtendimentos();
        tela.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastrarAtendimento tela = new CadastrarAtendimento();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CadastrarPet tela = new CadastrarPet();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ListaGerenciarVeterinarios tela = new ListaGerenciarVeterinarios();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CadastrarVeterinario tela = new CadastrarVeterinario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() == 2) {
            int linhaSelecionada = jTable1.getSelectedRow();
            
            if (linhaSelecionada != -1) {
                LocalDate hoje = java.time.LocalDate.now();
                List<Atendimento> agendaHoje = new java.util.ArrayList<>();

                if (AtendimentoController.listaAtendimentos != null) {
                    for (Atendimento a : AtendimentoController.listaAtendimentos) {
                        if (a.getData().equals(hoje)) {
                            agendaHoje.add(a);
                        }
                    }
                }

                Collections.sort(agendaHoje, Comparator.comparing(Atendimento::getHora));

                if (linhaSelecionada < agendaHoje.size()) {
                    Atendimento atendimentoAlvo = agendaHoje.get(linhaSelecionada);

                    VisualizarAtendimento tela = new VisualizarAtendimento(atendimentoAlvo);    
                    
                    tela.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosed(java.awt.event.WindowEvent e) {
                            carregarAgendaDoDia(); 
                        }
                    });
                    
                    tela.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarNovoTutor;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenuItem gerenciarTutores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
