package clinicaveterinaria.view;

import clinicaveterinaria.controller.AtendimentoController;
import clinicaveterinaria.model.Atendimento;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    public Menu() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/clinicaveterinaria/imagens/icon.png")).getImage());
        carregarAgendaDoDia();
    }

    private void carregarAgendaDoDia() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 

        modelo.setColumnIdentifiers(new String[] {"Veterinário", "Espécie", "Nome", "Atendimento", "Horário"});

        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("HH:mm");

        if (clinicaveterinaria.controller.AtendimentoController.listaAtendimentos != null) {
            java.util.List<clinicaveterinaria.model.Atendimento> agendaHoje = new java.util.ArrayList<>();

            for (clinicaveterinaria.model.Atendimento a : clinicaveterinaria.controller.AtendimentoController.listaAtendimentos) {
                if (a.getData().equals(hoje)) {
                    agendaHoje.add(a);
                }
            }

            java.util.Collections.sort(agendaHoje, java.util.Comparator.comparing(clinicaveterinaria.model.Atendimento::getHora));

            for (clinicaveterinaria.model.Atendimento a : agendaHoje) {
                modelo.addRow(new Object[]{
                    a.getVetResponsavel().getNome(),
                    a.getPetAtendido().getEspecie().toString(),
                    a.getPetAtendido().getNome(),
                    a.getProcedimento().name(),
                    a.getHora().format(formatoHora)
                });
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jMenu4 = new javax.swing.JMenu();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cadastrarNovoTutor = new javax.swing.JMenuItem();
        gerenciarTutores = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        btnVoltar.setText("Encerrar Operação");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("AGENDA DO DIA:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Veterinário", "Espécie", "Nome", "Atendimento", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnAtualizar.setText("Atualizar Janela");
        btnAtualizar.addActionListener(this::btnAtualizarActionPerformed);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicaveterinaria/imagens/menu.jpg"))); // NOI18N

        jMenu1.setText("Cadastros");

        jMenuItem7.setText("Cadastrar Novo Veterinário");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Gerenciar Veterinários");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu1.add(jMenuItem8);
        jMenu1.add(jSeparator1);

        cadastrarNovoTutor.setText("Cadastrar Novo Tutor");
        cadastrarNovoTutor.addActionListener(this::cadastrarNovoTutorActionPerformed);
        jMenu1.add(cadastrarNovoTutor);

        gerenciarTutores.setText("Gerenciar Tutores");
        gerenciarTutores.addActionListener(this::gerenciarTutoresActionPerformed);
        jMenu1.add(gerenciarTutores);
        jMenu1.add(jSeparator2);

        jMenuItem11.setText("Cadastrar Novo Pet");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu1.add(jMenuItem11);

        jMenuItem12.setText("Gerenciar Pets");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu1.add(jMenuItem12);
        jMenu1.add(jSeparator5);

        jMenuBar1.add(jMenu1);

        jMenu5.setText("Agendamentos");

        jMenuItem1.setText("Agendar Novo Atendimento");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Histórico de Agendamentos");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu5.add(jMenuItem2);
        jMenu5.add(jSeparator3);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnAtualizar))
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarNovoTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoTutorActionPerformed
        CadastrarTutor novoTutor = new CadastrarTutor();
        novoTutor.setVisible(true);
    }//GEN-LAST:event_cadastrarNovoTutorActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ListaGerenciarPets tela = new ListaGerenciarPets();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        carregarAgendaDoDia();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void gerenciarTutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarTutoresActionPerformed
        ListaGerenciarTutores tela = new ListaGerenciarTutores();
        tela.setVisible(true);
    }//GEN-LAST:event_gerenciarTutoresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListaGerenciarAtendimentos tela = new ListaGerenciarAtendimentos();
        tela.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastrarAtendimento tela = new CadastrarAtendimento();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        CadastrarPet tela = new CadastrarPet();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ListaGerenciarVeterinarios tela = new ListaGerenciarVeterinarios();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CadastrarVeterinario tela = new CadastrarVeterinario();
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() == 2) {
            int linhaSelecionada = jTable1.getSelectedRow();
            
            if (linhaSelecionada != -1) {
                java.time.LocalDate hoje = java.time.LocalDate.now();
                java.util.List<clinicaveterinaria.model.Atendimento> agendaHoje = new java.util.ArrayList<>();

                if (clinicaveterinaria.controller.AtendimentoController.listaAtendimentos != null) {
                    for (clinicaveterinaria.model.Atendimento a : clinicaveterinaria.controller.AtendimentoController.listaAtendimentos) {
                        if (a.getData().equals(hoje)) {
                            agendaHoje.add(a);
                        }
                    }
                }

                java.util.Collections.sort(agendaHoje, java.util.Comparator.comparing(clinicaveterinaria.model.Atendimento::getHora));

                if (linhaSelecionada < agendaHoje.size()) {
                    clinicaveterinaria.model.Atendimento atendimentoAlvo = agendaHoje.get(linhaSelecionada);

                    VisualizarAtendimento tela = new VisualizarAtendimento(atendimentoAlvo);    
                    
                    tela.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosed(java.awt.event.WindowEvent e) {
                            carregarAgendaDoDia(); 
                        }
                    });
                    
                    tela.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JMenuItem cadastrarNovoTutor;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenuItem gerenciarTutores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
