package clinicaveterinaria.view;

import clinicaveterinaria.controller.AtendimentoController;
import clinicaveterinaria.model.Atendimento;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.ImageIcon;

// View do Menu Principal do sistema, ele tem o caminho para todas as outras sessões
public class Menu extends javax.swing.JFrame {
    private List<Atendimento> agenda;
    
    public Menu() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/clinicaveterinaria/imagens/icon.png")).getImage());
        carregarAgendaDoDia();
        
        // Garante que a agenda do dia sempre esteja atualizada, para em caso de edição de Agendamentos
        this.addWindowListener(
                new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowActivated(java.awt.event.WindowEvent e) {
                        carregarAgendaDoDia();
                    }
                }
            );  
    }

    private void carregarAgendaDoDia() {
        DefaultTableModel modelo = (DefaultTableModel) agendaDia.getModel();
        modelo.setRowCount(0);

        this.agenda = AtendimentoController.getAtendimentosDoDia();

        for (Atendimento a : agenda) {
             modelo.addRow(new Object[]{
                a.getVetResponsavel().getNome(),      
                a.getPetAtendido().getEspecie(),      
                a.getPetAtendido().getNome(),         
                a.getProcedimento().name(),           
                a.getHora()      
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        agendaDia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cadastros = new javax.swing.JMenu();
        cadastrarVet = new javax.swing.JMenuItem();
        gerenciarVet = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cadastrarTutor = new javax.swing.JMenuItem();
        gerenciarTutor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cadastrarPet = new javax.swing.JMenuItem();
        gerenciarPet = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        agendamentos = new javax.swing.JMenu();
        historicoAgendamentos = new javax.swing.JMenuItem();
        novoAtendimento = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("AGENDA DO DIA:");

        agendaDia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        agendaDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Veterinário", "Espécie", "Nome", "Atendimento", "Horário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        agendaDia.setRowHeight(30);
        agendaDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendaDiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(agendaDia);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicaveterinaria/imagens/Menu.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("(Para visualizar clique duas vezes no atendimento desejado)");

        cadastros.setText("Cadastros");
        cadastros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cadastrarVet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarVet.setText("Cadastrar Novo Veterinário");
        cadastrarVet.addActionListener(this::cadastrarVetActionPerformed);
        cadastros.add(cadastrarVet);

        gerenciarVet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gerenciarVet.setText("Gerenciar Veterinários");
        gerenciarVet.addActionListener(this::gerenciarVetActionPerformed);
        cadastros.add(gerenciarVet);
        cadastros.add(jSeparator1);

        cadastrarTutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarTutor.setText("Cadastrar Novo Tutor");
        cadastrarTutor.addActionListener(this::cadastrarTutorActionPerformed);
        cadastros.add(cadastrarTutor);

        gerenciarTutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gerenciarTutor.setText("Gerenciar Tutores");
        gerenciarTutor.addActionListener(this::gerenciarTutorActionPerformed);
        cadastros.add(gerenciarTutor);
        cadastros.add(jSeparator2);

        cadastrarPet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastrarPet.setText("Cadastrar Novo Pet");
        cadastrarPet.addActionListener(this::cadastrarPetActionPerformed);
        cadastros.add(cadastrarPet);

        gerenciarPet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gerenciarPet.setText("Gerenciar Pets");
        gerenciarPet.addActionListener(this::gerenciarPetActionPerformed);
        cadastros.add(gerenciarPet);
        cadastros.add(jSeparator5);

        jMenuBar1.add(cadastros);

        agendamentos.setText("Agendamentos");
        agendamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        historicoAgendamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        historicoAgendamentos.setText("Histórico de Atendimentos");
        historicoAgendamentos.addActionListener(this::historicoAgendamentosActionPerformed);
        agendamentos.add(historicoAgendamentos);

        novoAtendimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        novoAtendimento.setText("Cadastrar Novo Atendimento");
        novoAtendimento.addActionListener(this::novoAtendimentoActionPerformed);
        agendamentos.add(novoAtendimento);
        agendamentos.add(jSeparator3);

        jMenuBar1.add(agendamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarTutorActionPerformed
        CadastrarTutor novoTutor = new CadastrarTutor();
        novoTutor.setVisible(true);
    }//GEN-LAST:event_cadastrarTutorActionPerformed

    private void gerenciarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarPetActionPerformed
        ListaGerenciarPets tela = new ListaGerenciarPets();
        tela.setVisible(true);
    }//GEN-LAST:event_gerenciarPetActionPerformed

    private void gerenciarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarTutorActionPerformed
        ListaGerenciarTutores tela = new ListaGerenciarTutores();
        tela.setVisible(true);
    }//GEN-LAST:event_gerenciarTutorActionPerformed

    private void historicoAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historicoAgendamentosActionPerformed
        ListaGerenciarAtendimentos tela = new ListaGerenciarAtendimentos();
        tela.setVisible(true);
    }//GEN-LAST:event_historicoAgendamentosActionPerformed

    private void novoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoAtendimentoActionPerformed
        CadastrarAtendimento tela = new CadastrarAtendimento();
        tela.setVisible(true);
    }//GEN-LAST:event_novoAtendimentoActionPerformed

    private void cadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarPetActionPerformed
        CadastrarPet tela = new CadastrarPet();
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarPetActionPerformed

    private void gerenciarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarVetActionPerformed
        ListaGerenciarVeterinarios tela = new ListaGerenciarVeterinarios();
        tela.setVisible(true);
    }//GEN-LAST:event_gerenciarVetActionPerformed

    private void cadastrarVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarVetActionPerformed
        CadastrarVeterinario tela = new CadastrarVeterinario();
        tela.setVisible(true);
    }//GEN-LAST:event_cadastrarVetActionPerformed

    private void agendaDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendaDiaMouseClicked
        if (evt.getClickCount() == 2) {
            int linhaSelecionada = agendaDia.getSelectedRow();
            
            if (linhaSelecionada != -1 && agenda != null && linhaSelecionada < agenda.size()) {
                Atendimento atendimentoAlvo = agenda.get(linhaSelecionada);
                VisualizarAtendimento tela = new VisualizarAtendimento(atendimentoAlvo);
                
                tela.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        carregarAgendaDoDia(); 
                    }
                });
                
                tela.setVisible(true);
            }
        }
    }//GEN-LAST:event_agendaDiaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable agendaDia;
    private javax.swing.JMenu agendamentos;
    private javax.swing.JMenuItem cadastrarPet;
    private javax.swing.JMenuItem cadastrarTutor;
    private javax.swing.JMenuItem cadastrarVet;
    private javax.swing.JMenu cadastros;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenuItem gerenciarPet;
    private javax.swing.JMenuItem gerenciarTutor;
    private javax.swing.JMenuItem gerenciarVet;
    private javax.swing.JMenuItem historicoAgendamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem novoAtendimento;
    // End of variables declaration//GEN-END:variables
}
